### ISSUE TITLE
[Question] How long does the battery lasts for the wireless keyboard?

### ISSUE THREAD

**Issue by Niryo** [rafaeldelboni/buildlogs#11]
First of all, thanks for the extremely detailed guides! those are greats, really.
Now for my question- I want to build a wireless corne from [this guid](https://github.com/rafaeldelboni/buildlogs/blob/main/crkbd-choc-spaced-switch.md), but I am a bit concerned about the battery life with the 130 mah battery. in your experience, how long does it lasts from full charge to empty with heavy usage? (software developer here)

**Comment by rafaeldelboni** [comment]
Hi Niryo, thanks a lot for the feedback, I really appreciate it!

Since I started using ZMK firmware-based keyboards, I've had issues with battery life, even when using the Corne with a bigger battery. So, after some investigating, I enabled the deep sleep feature of ZMK on my keyboards. This feature puts the keyboard into a deep sleep state after a period of inactivity (I set mine to 30 minutes).

The only downside of using this feature is that waking up the keyboard takes a few seconds (usually 3-5).

But the benefits are fantastic! I'm using TOTEM all day as a software developer, and the battery lasts for a month or more. The Corne also lasts over 2 months easily.

Here's how you configure the deep sleep:
[ZMK Totem Configuration](https://github.com/rafaeldelboni/zmk-totem/blob/master/config/totem.conf#L3-L9)

By default, the Totem firmware doesn't have wakeup-source enabled. This is necessary for the keyboard to scan all keys as a wake-up source. Without this line, you'll need to turn your keyboard off and on to wake it up:
[Totem DTSI Configuration](https://github.com/rafaeldelboni/zmk-totem/blob/master/config/boards/shields/totem/totem.dtsi#L36)

And here's some official documentation:
[ZMK Power Configuration](https://zmk.dev/docs/config/power#idlesleep)

**Comment by Niryo** [comment]
Cool, thanks! I will try it out once my build is ready:)
